export enum ActionType {
	GET_CURRENT_USER_START = "GET_CURRENT_USER_START",
	GET_CURRENT_USER_SUCCESS = "GET_CURRENT_USER_SUCCESS",
	GET_CURRENT_USER_FAIL = "GET_CURRENT_USER_FAIL",
	GET_CURRENT_USER_ERROR = "GET_CURRENT_USER_ERROR",
	GET_PROJECTS_ERROR = "GET_PROJECTS_ERROR",
	GET_PROJECTS_START = "GET_PROJECTS_START",
	GET_PROJECTS_SUCCESS = "GET_PROJECTS_SUCCESS",
	SIGN_IN_ERROR = "SIGN_IN_ERROR",
	SIGN_IN_START = "SIGN_IN_START",
	SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS",
}
